### PR TITLE
Issue 2195 fffw -- reduced size

### PR DESCRIPTION
**Pull request by fffw**
I added jQuery back as it is required by `select2.js`, but that won't affect ultimate size.

Changed files are [app/index.html](https://github.com/getlantern/lantern-ui/compare/issue-2195...issue-2195-fffw?expand=1#diff-b9707fe88797285e93483456d1389b61) and [gulpfile.js](https://github.com/getlantern/lantern-ui/compare/issue-2195...issue-2195-fffw?expand=1#diff-b9e12334e9eafd8341a6107dd98510c9).

This PR relates to https://github.com/getlantern/lantern/issues/2240

### CODE REVIEW

**Comment by myleshorton** [comment]
Looks great to me @fffw! I did have to install a few other npm modules:

npm install gulp-usemin
npm install gulp-uglify
npm install gulp-minify-html
npm install gulp-minify-css
npm install gulp-rev
npm install del

Should that first batch have somehow come with npm install gulp?

**Comment by fffw** [comment]
Oh forgot to mention that simply `npm install` will work, updated README

**Comment by myleshorton** [comment]
Cool. I actually also first did just 

```
npm install gulp
```

but I still had to do all of the above one by one. It seemed odd, but that's what happened. Did you not have to do that?

**Comment by fffw** [comment]
I just tried `npm rm` several packages and simply `npm install`, it installed all required modules specified in 'packages.json'.

Don't 'npm install gulp', just 'npm install' to install all required packages.

**Comment by myleshorton** [comment]
Oh right! I'm still a bit of an npm newbie. Thanks.

**Comment by myleshorton** [comment]
I think we'll probably want to actually check in dist, @fffw, and to have both lantern main use that during development and to have the installers use that. Does that make sense? I'd like to avoid having a separation between production and development.

**Comment by fffw** [comment]
@myleshorton added.

**Comment by oxtoacart** [comment]
@fffw @myleshorton Do I understand correctly that we now have 2 JavaScript build systems, bower and gulp?

**Comment by fffw** [comment]
@oxtoacart Bower is a package management system, Gulp is a build system, both is required.

**Comment by oxtoacart** [comment]
@fffw Sorry, I confused bower and grunt.  Are we still using grunt, or has that been replaced by Gulp?

**Comment by fffw** [comment]
@oxtoacart I think we were not using any build system on lantern-ui before. the website is using Grunt.

**Comment by oxtoacart** [comment]
Thanks @fffw!  BTW, nice work on getting the size of the UI down.

Not for Valencia, but eventually I would love to see us simplify all of this.  We have a very small UI (just one page, one modal dialog for now) and the amount of complexity in our web resources seems out of proportion with the size of the UI.

**Comment by fffw** [comment]
@oxtoacart We can have minified library files under `lib` and cease to use bower or gulp anymore. But we can also have these tool to ease our development of UI part, and just forget it and use the `dist` directory elsewhere. Either way works.

**Comment by oxtoacart** [comment]
@fffw It's actually not so much the build process that I'd like to simplify (I like your idea of just using a lib folder), but just the overall number of dependencies (which is currently 20 javascript libraries).  @atavism can testify to the pain that was involved in upgrading Angular and Angular-bootstrap in particular, and I suspect that a lot of our dependencies are on libraries from which we're using only a small part of what they do, and could just as easily have done it ourselves.  Given our functionality, it seems like we could do what we need with just the following libraries:

- Some sort of databinding library (preferably not Angular but ractive.js or something like that)
- analytics.js (for Google Analytics)
- d3 (provides useful layout and visualization algorithms that would be hard to do on our own)
- topojson (for generating the world map)
- maybe lodash (provides some useful functional constructs, but it's something more for a new developer to learn)
- mabye jsonpatch (depending on our backend protocol)

**Comment by fffw** [comment]
@oxtoacart Simplifying libraries is definitely required. I can touch it when have time.

**Comment by myleshorton** [comment]
Nice LGTM @fffw. Agreed on simplifying dependencies. I agree @oxtoacart avoiding importing stuff for something small we could do ourselves (or copy ourselves depending on the license) is desirable, especially with size as such an important consideration.

**Pull request merged**
